export VLLM_ATTENTION_BACKEND=XFORMERS

python3 -m verl.trainer.main_ppo \
data.train_files=/workspace/TinyZero/data/arth_super_simple/train.parquet \
data.val_files=/workspace/TinyZero/data/arth_super_simple/test.parquet \
data.train_batch_size=32 \
data.val_batch_size=256 \
data.max_prompt_length=256 \
data.max_response_length=32 \
actor_rollout_ref.model.path=Qwen/Qwen2.5-0.5B \
actor_rollout_ref.actor.optim.lr=1e-6 \
actor_rollout_ref.actor.ppo_mini_batch_size=16 \
actor_rollout_ref.actor.ppo_micro_batch_size=4 \
actor_rollout_ref.rollout.log_prob_micro_batch_size=4 \
actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
actor_rollout_ref.ref.log_prob_micro_batch_size=4 \
critic.optim.lr=1e-5 \
critic.model.path=Qwen/Qwen2.5-0.5B \
critic.ppo_micro_batch_size=4 \
algorithm.kl_ctrl.kl_coef=0.001 \
trainer.logger=['wandb'] \
+trainer.val_before_train=False \
trainer.default_hdfs_dir=null \
trainer.n_gpus_per_node=2 \
trainer.nnodes=1 \
trainer.save_freq=100 \
trainer.test_freq=50 \
trainer.project_name=TinyZero \
trainer.experiment_name=debug_runpod \
trainer.total_training_steps=1 \
trainer.total_epochs=1 2>&1 | tee verl_demo.log \